/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package windows;

import basicDataStructure.DiaryDescription;
import java.lang.reflect.Method;

/**
 *
 * @author Administrator
 */
public class Panel_OneDiaryElement extends javax.swing.JPanel {

    
    private I_Message_From_PanelOneDiary_To_MFrame giveDiary_To_MFrame;
    private int diaryID;
    
    public void setRespondingInterface(I_Message_From_PanelOneDiary_To_MFrame method)
    {
        giveDiary_To_MFrame=method;
    }
    public void setDiaryTitle(String title){
        jL_title.setText(title);
        
    }
    public void setDiaryID(int id)
    {
        diaryID=id;
    }
    public int getDiaryID()
    {
        return diaryID;
    }
    public String getDiaryTitle(){
        return jL_title.getText();
    }
    public void setDiaryTime(String t){
        jL_time.setText(t);
    }
    public String getDiaryTime(){
        return jL_time.getText();
    }
    public void setDiaryStringContent(String con){
             if(con.length()>36)
                 con=con.substring(0,34)+"...";
        jL_content.setText(con);
    }
    public String getDiaryStringContent(){
        return jL_content.getText();
    }
    public void setDiaryType(String type){
        jL_type.setText(type);
    }
    public String getDiaryType(){
        return jL_type.getText();
    }
            
    /**
     * Creates new form DiaryPanel
     */    
    public Panel_OneDiaryElement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_time = new javax.swing.JLabel();
        jL_title = new javax.swing.JLabel();
        jL_type = new javax.swing.JLabel();
        jL_content = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        jL_time.setFont(new java.awt.Font("宋体", 2, 12)); // NOI18N
        jL_time.setText("2013-10-19 08:33");

        jL_title.setFont(new java.awt.Font("仿宋", 1, 12)); // NOI18N
        jL_title.setText("这是一个标题");

        jL_type.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jL_type.setForeground(new java.awt.Color(102, 0, 102));
        jL_type.setText("分类名");

        jL_content.setText("这是我的文本内容，是不是应该多写一点，让他可以见到边框上呗...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL_time, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_title, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jL_type, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_time)
                    .addComponent(jL_title)
                    .addComponent(jL_type))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_content, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        if(this.hasFocus())
            return;
        setBackground(new java.awt.Color(204, 255, 204));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        if(this.hasFocus())
            return;
        setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.grabFocus();
        giveDiary_To_MFrame.setWhichElementIsSelected(this);
    }//GEN-LAST:event_formMouseClicked

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
          setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_formFocusLost

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
       setBackground(new java.awt.Color(153, 204, 255));
    }//GEN-LAST:event_formFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_content;
    private javax.swing.JLabel jL_time;
    private javax.swing.JLabel jL_title;
    private javax.swing.JLabel jL_type;
    // End of variables declaration//GEN-END:variables
}
